
[workspace]
authors = ["Sylvia E <sylviae2@illinois.edu>"]
channels = ["conda-forge"]
name = "semantic_summation"
platforms = ["osx-arm64"]
version = "0.1.0"


[dependencies]
sqlalchemy = ">=2.0.48,<3"
r-base = ">=4.5.3,<4.6"
r-lme4 = ">=1.1_38,<2"
matplotlib = ">=3.10.8,<4"
r-ggplot2 = ">=4.0.2,<5"
r-purrr = ">=1.2.1,<2"
nltk = ">=3.9.4,<4"
pandas = ">=3.0.1,<4"
inflect = ">=7.5.0,<8"
networkx = ">=3.6.1,<4"
streamlit = ">=1.40.0,<2"
plotly = ">=5.0,<7"
